### ISSUE TITLE
Allow to get a single entry by ID

### ISSUE THREAD

**Issue by tobias-f** [NicolasRitouet/dpd-fileupload#16]
It would be nice to get a single entry of the collection by sending the id. For example:

http://localhost:2403/upload
returns all files in the collection

http://localhost:2403/upload/123412341234
returns only file with id='123412341234'

Thanks

**Comment by NicolasRitouet** [comment]
I wanted to build this feature a while ago, but I was asking myself a question:
in this case, should I return a json object containing all information about the file or the file itself?
Was do you guys think?

**Comment by EvilDrW** [comment]
I just started using this module and ran into this issue very quickly.
When you say "the file itself" are you meaning the filename or something else?  Either way, I think I'd want the json object... the creationDate field in particular would be really useful to me.

**Comment by NicolasRitouet** [comment]
I agree that we need to return the full json object of the file.
I don't have time to build this feature right now, but any PR is more than welcome!

**Comment by EvilDrW** [comment]
I'll see what I can do!

**Comment by EvilDrW** [comment]
this was added in #40

**Comment by NicolasRitouet** [comment]
true, thx :)
