### ISSUE TITLE
dpd-fileupload only gets the first url param. Am I the one only experiencing this?

### ISSUE THREAD

**Issue by j-a-y-c-e-e** [NicolasRitouet/dpd-fileupload#18]
Haven't look into why is it happening in my dev env but thought I'd post it.

**Comment by NicolasRitouet** [comment]
Hi @j-a-y-c-e-e 
can you provide an example? Or a way to reproduce it?

**Comment by NicolasRitouet** [comment]
Hey @j-a-y-c-e-e 
It's been a few months, I'm closing this issue.
If you still have this issue, can you please reopen this ticket and provide more information.
