### ISSUE TITLE
Error loading module node_modules/dpd-fileupload

### ISSUE THREAD

**Issue by tscole** [NicolasRitouet/dpd-fileupload#26]
Installed dpd-fileupload by running "npm install dpd-fileupload --save" in my projects root dir.

Trying to run dpd now results in the error:

Error loading module node_modules/dpd-fileupload
Error: Cannot find module 'deployd/lib/resource'

**Comment by tscole** [comment]
Following these instructions:

"You should install deployd in your app directory.

cd your-app
npm install deployd"

Found here: https://github.com/deployd/dpd-importer/issues/4 seems to fix it.

**Comment by moorthi07** [comment]
Running "dpdjs" task (grunt-dpdjs package)

Error loading module node_modules/dpd-fileupload
TypeError: Cannot read property 'options' of undefined
Any idea why this happens?
