### ISSUE TITLE
event "on upload" does not contain "this"

### ISSUE THREAD

**Issue by kvdmolen** [NicolasRitouet/dpd-fileupload#29]
I would like to access the unique `filename` in the `on upload` event,
but it does not contain the `this` element

**Comment by beforeadream** [comment]
Exactly!

returns empty object

**Comment by NicolasRitouet** [comment]
@kvdmolen @beforeadream 
I just merged a PR that contains what you've been looking for.

**Comment by beforeadream** [comment]
@NicolasRitouet thanks alot! :+1: :+1: :+1:

**Comment by kvdmolen** [comment]
:+1:
