### ISSUE TITLE
Sending additional data through POST

### ISSUE THREAD

**Issue by murray484** [NicolasRitouet/dpd-fileupload#62]
Is there a way to send additional data to be included with the file through POST parameters?  In my case, I am using dropzone.js to upload the images, and would like to attach other information by appending it to the form data.  Is this possible?

**Comment by kkrishnan90** [comment]
Hi there... I think I have tried doing that and it was a success. When you mean attaching some json properties with the image ? If so, yes its possible. Try supplying parameters through POST url. 

Ex : localhost:2403/fileupload?username=kkrishnan90&isprofileimage=true

The above POST will yield you the following response structure along with your included properties in JSON. 
```
[
  {
    "username": "kkrishnan90",
    "isprofileimage": true,
    "filename": "c3a83369f19ea6352dc2ca2edc5fbc6c.png",
    "originalFilename": "warning-exclamation-sign.png",
    "filesize": 1162,
    "creationDate": 1477594024454,
    "type": "image/png",
    "id": "32d1097fa675585c"
  }
]
```
**Please note the supplied username and isprofileimage boolean value in the JSON response**

Let me know if this fixes your issue.
