### ISSUE TITLE
not able to get single file

### ISSUE THREAD

**Issue by FunnyDevs** [NicolasRitouet/dpd-fileupload#71]
Hi! I have uploaded one file on a directory, but i'm not able to get this file following your rule.
my directory is "localhost:3000/files/photo/filename"

if i move filename to another public directory, like this "localhost:3000/other/", i was able to get the file calling "localhost:3000/other/filename"

**Comment by NicolasRitouet** [comment]
I don't really get your question, can you be more precise?
