### ISSUE TITLE
Creating a relationship with other collections?

### ISSUE THREAD

**Issue by madd86** [NicolasRitouet/dpd-fileupload#81]
How would I go about doing? 

I did it with a collection to collection, but with fileupload to collection I can't because I can't add properties.

This is my code:

```
dpd.posts.put({id: this.post}, {files: {$push: this.id}}, function(result, err) {
  if (err) cancel(err);
});
```

Since "post" property doesn't exist it doesn't read when I insert it into the body.

So, how could I do a relation with this module?

**Comment by NicolasRitouet** [comment]
The solution I used to solve this issue was to store the files in a subdir with the id of your other relation. An example here: https://github.com/NicolasRitouet/kinoa/blob/master/public/app/pages/companyPage/companyPage-controller.js#L304
This is not really clean though, but it works.
Another solution could be to add a collection to handle the relation between your file and the other entity.

**Comment by madd86** [comment]
@NicolasRitouet wouldn't it be better to add a custom property on the module?

I did try to add it by editing line 100 on index.js and added: ``` postId, ```

And then I added on line 134 this:

```
                } else if (propertyName === 'postId') {
					postId = req.query[propertyName];
```

But it doesn't really work.

Wonder how to add it.

**Edit**:

I also edited my code to the following:

```
dpd.posts.put({id: this.subdir}, {files: {$push: this.id}}, function(result, err) {
  if (err) cancel(err);
});
```

Posted with 2 params, the filename (as the file) and the subdir with the id of the post, however, I still get this message:

```
{
	"message": "must provide id to update an object",
	"statusCode": 400,
	"status": 400
}
```

I wonder if it's because it's a multipart? Because I can't create a subdir regardless of using it as id collector or not.

Edit 2:

I get it, subdir is actually a param and to call it I would have to use query. And my extra thing did work, postId. I changed my code to: ``` dpd.posts.put({id: query.postId} ```

The problem now is that I can't use ```this.id``` because it returns null. Trying to figure out why.

**Comment by madd86** [comment]
Well.. I wanted to do less work on the client as possible, therefore I wanted it to return as part of an array on my other collection.

I guess I'll have to get the file from /fileupload get, with this on the get event:

```
dpd.fileupload.get({postId: query.postId}, function(data, status, headers, config) {
});
```
